name: Create Release

on:
    create:
jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Create a release draft for a version tag
              id: create-release-draft
              uses: ecampidoglio/auto-release-draft@v1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Print the URL of the release draft
              if: steps.create-release-draft.outputs.release-url != ''
              run: echo ${{ steps.create-release-draft.outputs.release-url }}
